steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'functions', 'deploy',
      'my-show',
      '--trigger-http',
      '--runtime', 'go116',
      '--entry-point', 'SendMyShowNoti',
    ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'functions', 'deploy',
      'scheduled-show',
      '--trigger-http',
      '--runtime', 'go116',
      '--entry-point', 'SendScheduledShowNoti',
    ]
